export const easyList = [
    {
        name: "Fromager d'Affinois",
        url: "images/cheese/daffinois.jpeg",
        wrongNames: ["Brie Fermier", "Brebirousse d'Argental", "Florette"],
        milk: "Pasteurized Cow",
        origin: "France",
        catagory: "Soft Ripened, Double Creme",
        blurb: "An alternative to brie that is more creamy and buttery. Easy choice for a crowd pleasing soft cheese."
    },
    {
        name: "Brebirousse d'Argental",
        url: "images/cheese/brebirousse.jpeg",
        wrongNames: ["Taleggio", "Fromager d'Affinois", "Epoisses"],
        milk: "Pasteurized Sheep",
        origin: "France",
        catagory: "Soft Ripened, Double Creme",
        blurb: "The orange on the rind might make you think it is a washed rind, but it is actually annato that gives it that color.",
    },
    {
        name: "Mothais sur Feuille",
        url: "images/cheese/mothais.jpeg",
        wrongNames: ["Chabichou", "Bonne Buche", "Perail de Brebis"],
        milk: "Pasteurized Goat",
        origin: "France",
        catagory: "Soft Ripened, Geotrichum, Small Format",
        blurb: "This classic french goat is aged on a chestnut leaf."
    },
    {
        name: "Moliterno al Tartufo",
        url: "images/cheese/moliterno.jpeg",
        wrongNames: ["Boschetto al Tartufo", "Truffle Tremor", "Truffle Gouda"],
        milk: "Pasteurized Sheep",
        origin: "Sardinia, Italy",
        catagory: "Aged, Hard, Flavored",
        blurb: "This cheese has intense truffle flavor which comes from its black truffle paste veining.",
    },
    {
        name: "Prairie Breeze Cheddar",
        url: "images/cheese/pbreeze.jpeg",
        wrongNames: ["Gruyere", "Monterey Jack", "Havarti"],
        milk: "Pasteurized Cow",
        origin: "Milton, Iowa",
        catagory: "Aged, Hard, Cheddar",
        blurb: "Milton Creamery uses fresh milk from the Amish and Mennonite family farms down the road.",
    },
    {
        name: "Gruyere",
        url: "images/cheese/gruyere.jpeg",
        wrongNames: ["Golden Fleece", "Estero Gold", "Old Quebec Cheddar"],
        milk: "Raw Cow",
        origin: "Switzerland",
        catagory: "Aged, Hard, Alpine",
        blurb: "Gruyere has been made for over 800 years. It must be produced in the Gruyères region of Switzerland, is made using milk from cows that graze on the region's lush pastures, and is aged in caves.",
    },
    {
        name: "Pecorino Romano",
        url: "images/cheese/romano.jpeg",
        wrongNames: ["Pecorino Toscano", "Gruyere", "Parmigiano Reggiano"],
        milk: "Pasteurized Sheep",
        origin: "Sardinia, Italy",
        catagory: "Hard, Aged, Grating",
        blurb: "This classic grating cheese is mostly made on the island of Sardina, not in Rome like one might guess.",
    },
    {
        name: "Fontina Val D'Aosta",
        url: "images/cheese/fontina.jpeg",
        wrongNames: ["Comte", "Wagon Wheel", "Raclette"],
        milk: "Raw Cow",
        origin: "Aosta Valley, Italy",
        catagory: "Semi Hard, Aged, Washed Rind",
        blurb: "This is the original, named protected Fontina. Production dates back to the 12th century.",
    },
    {
        name: "Brie Fermier",
        url: "images/cheese/briefermier.jpeg",
        wrongNames: ["Fromage D'affinois", "Brillat Savarin", "Camembert dell'Alta Langa"],
        milk: "Pasteurized Cow",
        origin: "France",
        catagory: "Soft Ripened",
        blurb: "Fermier means farmstead, which means the cheese maker uses milk from their own herd of animals.",
    },
    {
        name: "Brillat Savarin",
        url: "images/cheese/brillat.jpeg",
        wrongNames: ["Fromage D'affinois", "Foggy Morning", "Chabichou"],
        milk: "Pasteurized Cow",
        origin: "France",
        catagory: "Soft Ripened, Triple Creme",
        blurb: "Named after Jean Anthelme Brillat-Savarin, a French lawyer and gastronome known for his influential work The Physiology of Taste, which explores the art and philosophy of food.",
    },
    {
        name: "Cambozola Black Label",
        url: "images/cheese/cambozola.jpeg",
        wrongNames: ["Roquefort", "Appenzeller Black Label", "Gorgonzola"],
        milk: "Pasteurized Cow",
        origin: "Germany",
        catagory: "Soft Ripened, Blue, Double Creme",
        blurb: "This German blue is coated in a thin layer of Penicillium candidum mold, while the blue interior is caused by Penicillium roqueforti.",
    },
    {
        name: "Chabichou",
        url: "images/cheese/chabichou.jpeg",
        wrongNames: ["Brillat Savarin", "Coupole", "Besace du Berger"],
        milk: "Pasteurized Goat",
        origin: "Poitou, France",
        catagory: "Soft Ripened, Geotrichum",
        blurb: "Chabichou gained name protected status (AOC) in 1990, but that version is made with raw milk and cannot be imported into the US because it is younger than 60 days."
    },
    {
        name: "Cotswold",
        url: "images/cheese/cotswold.jpeg",
        wrongNames: ["4-Alarm Cheddar", "Leyden", "Raclette"],
        milk: "Pasteurized Cow",
        origin: "England",
        catagory: "Semi Hard, Flavored",
        blurb: "This cheese has chives throughout the paste and is a great melter."
    },
    {
        name: "Enrobe with Apricot",
        url: "images/cheese/enrobe.jpeg",
        wrongNames: ["Chabichou", "Crottin", "Enrobe with Mango"],
        milk: "Pasteurized Goat",
        origin: "France",
        catagory: "Fresh, Flavored",
        blurb: "Enrobe means 'coat' or 'cover' and this fresh goat cheese comes in many different varities it is enrobed with, such as cranberry, herbs, and peppercorns."
    },
    {
        name: "Ewephoria",
        url: "images/cheese/ewephoria.jpeg",
        wrongNames: ["Beemster", "Prima Donna", "Lamb Chopper"],
        milk: "Pasteurized Sheep",
        origin: "Netherlands",
        catagory: "Hard, Aged, Gouda",
        blurb: "Ewephoria was specially crafted for the American market by a Dutch cheesemaker who was aiming to create a sweeter sheeps milk cheese."
    },
    {
        name: "Valbreso Feta",
        url: "images/cheese/feta.jpeg",
        wrongNames: ["Monterey Jack", "Queso Fresco", "Halloumi"],
        milk: "Pasteurized Sheep",
        origin: "France",
        catagory: "Fresh, Feta",
        blurb: "Feta is a name protected cheese in Europe, and requires that it be made in Greece. As this is French, this cheese is not advertised or labeled by the producer as Feta."
    },
    {
        name: "Humboldt Fog",
        url: "images/cheese/hfog.jpeg",
        wrongNames: ["Morbier", "Bay Blue", "Bucheron"],
        milk: "Pasteurized Goat",
        origin: "Arcata, California",
        catagory: "Soft Ripened, Ash Ripened",
        blurb: "First created in 1992 by Mary Keehn, founder of Cyprus Grove, and is now one of the most well known American cheeses. The line of vegetable ash running through its center is inspired by the classic French cheese Morbier."
    },
    {
        name: "Manchego",
        url: "images/cheese/manchego.jpeg",
        wrongNames: ["Secret de Compostelle", "Drunken Goat", "Ewephoria"],
        milk: "Pasteurized Sheep",
        origin: "La Mancha, Spain",
        catagory: "Hard, Aged",
        blurb: "Manchego can only be made in the La Mancha region of Spain, using milk from Manchega sheep. It can be made with raw or pasteurized milk."
    },
    {
        name: "Prima Donna",
        url: "images/cheese/pdonna.jpeg",
        wrongNames: ["Pradera", "Ewephoria", "Beemster"],
        milk: "Pasteurized Cow",
        origin: "Netherlands",
        catagory: "Hard, Aged, Gouda",
        blurb: "Aged for about 12 months, Prima Donna has some of the tyrosine crystals that add a crunchy texture to its paste."
    },
    {
        name: "Pepper Jack",
        url: "images/cheese/pjack.jpeg",
        wrongNames: ["4-Alarm Cheddar", "Monterey Jack", "Colby Jack"],
        milk: "Pasteurized Cow",
        origin: "California",
        catagory: "Semi Hard",
        blurb: "An American original that is inexpensive and great for melting."
    },
    {
        name: "Parmigiano Reggiano",
        url: "images/cheese/reggiano.jpeg",
        wrongNames: ["Pecorino Romano", "Piave", "Grana Padano"],
        milk: "Raw Cow",
        origin: "Italy",
        catagory: "Hard, Aged, Grating",
        blurb: "A wheel of Parmigiano Reggiano must be aged a minimum of 12 months and weighs about 88 lbs (40 kg). One of the most common examples of umami flavor. "
    },
    {
        name: "Taleggio",
        url: "images/cheese/taleg.jpeg",
        wrongNames: ["Epoisses", "Rosso di Bufala", "Brebirousse d'Argental"],
        milk: "Pasteurized Cow",
        origin: "Lombardy, Italy",
        catagory: "Washed Rind",
        blurb: "Taleggio production dates back to the 9th century, making it one of Italys oldest cheeses."
    },
]
